### ISSUE TITLE
Cannot have more than 0 builds in queue for the account

### ISSUE THREAD

**Issue by 0xYao** [hashicorp/learn-terraform-aws-control-tower-aft#7]
# Description

After I ran `terraform apply` for the first time, I am getting this error

`Error: Lambda function (aft-lambda-layer-codebuild-invoker) returned error: ({"errorMessage": "An error occurred (AccountLimitExceededException) when calling the StartBuild operation: Cannot have more than 0 builds in queue for the account", "errorType": "AccountLimitExceededException", "stackTrace": ["  File \"/var/task/codebuild_invoker.py\", line 28, in lambda_handler\n    job_id = client.start_build(projectName=codebuild_project_name)[\"build\"][\"id\"]\n", "  File \"/var/runtime/botocore/client.py\", line 391, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/runtime/botocore/client.py\", line 719, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]})`

I deleted and recreated the CodeBuild projects after I added a valid payment method to the AFT management account (initially, there was no payment method associated with the account) per this [StackOverflow answer](https://stackoverflow.com/a/58945971). 

However, it's still not working 😢

**Comment by 0xYao** [comment]
p.s. I have not tried contacting AWS support

**Comment by ritsok** [comment]
Hello! Thanks for submitting this report. Based on the error message shared, it sounds like this might be an error relating to quotas in your AWS account, try contacting them for more guidance!
